### ISSUE TITLE
Mako highlighting extension not working with Komodo version 9

### ISSUE THREAD

**Issue by kashifpk** [creiht/komodomako#2]
Hey,

It seems the komodo 9 broke your code somehow. Here is the original discussion:

https://github.com/Komodo/KomodoEdit/issues/89

Can you take a look at it to see if it's a quick fix?

Thanks.

**Comment by creiht** [comment]
I will take a look at it, thanks for letting me know.

**Comment by creiht** [comment]
Could you try this build to see how it works for you?

https://community.activestate.com/files/mako_language-1.4.1-ko.xpi

The basics seem to work, but I haven't done web dev or mako templates in quite a while.  If you find any issues, please feel free to open a bug.

**Comment by kashifpk** [comment]
Yes, that fixed it. Thanks.

**Comment by creiht** [comment]
Great, thanks!
